name: Build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
    
  in-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive  # Ensure submodules are checked out

      - name: Install Dependencies
        run: python3 scripts/install_deps.py --all

      - name: Build project
        run: python3 scripts/build.py --emscripten_sdk=tmp/emsdk --ninja_path=tmp/ninja.exe --android_ndk=tmp/android_sdk/ndk/26.3.11.579264

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows_wasm_android
          path: build/OUT/*